.Dd January 12, 2020
.Os libzt 0.1
.Dt zt_test 3 PRM
.Sh NAME
.Nm zt_test
.Nd private representation of test state
.Sh SYNOPSIS
struct zt_test; /* opaque type */
.Sh DESCRIPTION
.Nm
is an opaque type that holds test state during execution. The test type is
passed as an argument to each test function.  It is further passed to both
.Fn zt_check
and
.Fn zt_assert
functions, to alter test state.
.Pp
Internally
.Nm
stores the outcome of the test as well as data required for non-local exit
necessary when
.Fn zt_assert
fails.
.Sh HISTORY
.Nm
first appeared in libzt 0.1
.Sh AUTHORS
.An "Zygmunt Krynicki" Aq Mt me@zygoon.pl
