name: Build and Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/checkout@v2
      with:
        repository: zyga/zmk
        path: zmk-snapshot
        fetch-depth: 0
    - name: Install zmk snapshot
      id: zmk
      run: |
        make -C zmk-snapshot
        sudo make -C zmk-snapshot install
    - name: Bootstrap the configuration system
      run: make configure
    - name: Run distcheck
      run: make distcheck -j2
    - name: Uninstall zmk snapshot
      if: ${{ steps.zmk.conclusion == 'success' }}
      run: sudo make -C zmk-snapshot uninstall
  macos:
    runs-on: macos-latest
    needs: linux
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/checkout@v2
      with:
        repository: zyga/zmk
        path: zmk-snapshot
        fetch-depth: 0
    - name: Install zmk snapshot
      id: zmk
      run: |
        make -C zmk-snapshot
        sudo make -C zmk-snapshot install
    - name: Bootstrap the configuration system
      run: make configure
    - name: Run distcheck
      run: make distcheck -j2
    - name: Uninstall zmk snapshot
      if: ${{ steps.zmk.conclusion == 'success' }}
      run: sudo make -C zmk-snapshot uninstall
  windows:
    runs-on: windows-latest
    needs: linux
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build with MSVC
        run: nmake /f Makefile.nmake.mk all
      - name: Run the test suite
        run: nmake /f Makefile.nmake.mk check
